---
title: "NNAR"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../src/model_4_nnar_model.R")
load("../data/processed/ts_train_data")
load("../data/processed/ts_test_data")
```


# Introduction

Apply a NNAR model to forecast benzene concentration levels for the next 25 days.


# Create NNAR model

```{r pressure, echo=FALSE}
model_4_nnar_model <- create_nnar_model(ts_train_data)
```


# Forecast the Next 25 Days (Test Dataset Length)

```{r}
model_4_forecast_values <- forecast_nnar(model_4_nnar_model, forecast_horizon = nrow(ts_test_data))
save(model_4_forecast_values, file = "../data/processed/model_4_forecast_values.RData")
```


# Plot Forecast vs Historical Data

```{r}
plot_nnar_forecast(model_4_forecast_values, ts_train_data, ts_test_data)
```


# Model Residuals

```{r}
checkresiduals(model_4_nnar_model)
```


# Model Residuals Test

```{r}
nnar_residuals <- residuals(model_4_nnar_model)
residuals_test(nnar_residuals)
```


# Evaluation Metrics

```{r warning=FALSE}
evaluation_metrics(as.numeric(ts_test_data), model_4_forecast_values$mean)
```
